spring:  
  cloud:
      gateway:
        default-filters:
          - name: TestFilter
        routes:
          - id: microservice1
            uri: http://localhost:8082
            predicates:
              - Path=/microservice1/**

          - id: microservice2
            uri: http://localhost:8081
            predicates:
              - Path=/microservice2/**