eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: serviceregistry,health,info
  info:
    env:
      enabled: true